In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('datasets/homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

**Data Preprocessing: Fill NA values with median value of a column**

In [3]:
df.bedrooms.median()

AttributeError: 'DataFrame' object has no attribute 'bedrooms'

In [4]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

AttributeError: 'DataFrame' object has no attribute 'bedrooms'

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
reg.intercept_

221323.00186540408

**Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old**

In [9]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [10]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

**Find price of home with 2500 sqr ft area, 4 bedrooms,  5 year old**

In [11]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])